# Generated by Django 4.2.6 on 2023-10-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='Student Name')),
                ('Email', models.EmailField(max_length=30, verbose_name='Student Email')),
            ],
        ),
    ]
