# Generated by Django 4.2.3 on 2023-10-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentadd', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
